
#-------------------- Redis ----------------------
redis.db=4

#-------------------- Diverse ----------------------
url.path=file:///home/rcs/opt/java/nordnetservice/src/test/resources/html/demo

#-------------------- Caffeine ----------------------
cache.options.expiry=30
cache.option.expiry=600
