
#-------------------- Spring Data Source ----------------------
spring.datasource.url=jdbc:postgresql://172.20.1.6:5432/trader_atest

#-------------------- Redis ----------------------
redis.db=6
redis.fetchOpeningPrice=false

#-------------------- Diverse ----------------------
url.path=file:///home/rcs/opt/java/nordnetservice/src/test/resources/html/demo

#-------------------- Caffeine ----------------------
cache.options.expiry=30
cache.option.expiry=600
